runtime: go115

env_variables:
  GCPPROJECT: "golangproject-319101"
  HTTPPORT: "8080"
  USEDB: "postgre_cloud_proxy" #postgre_cloud_proxy, postgre_remote or empty for SQLite
  DBINSTANCE: "videodb"
  DBREGION: "us-west4"
  DBHOST: "34.125.62.48"
  DBUSER: "postgres"
  DBPASSWORD: "Mybaby1021a"
  DBDRIVER: "cloudsqlpostgres"
  DBNAME: "postgres"
  DBPORT: "5432" 
  DBSSLMODE: "disable"
  DBTIMEZONE: "America/Los_Angeles"